### ISSUE TITLE
About pre-training

### ISSUE THREAD

**Issue by wangweiran0922** [dvlab-research/Simple-SR#15]
I would like to ask about how to train the 72 Gaussian kernels in the dictionary and how to modify their number？

**Comment by fenglinglwb** [comment]
Thanks for your interest. The kernels are empirically hand-crafted, with no need of training.

**Comment by wangweiran0922** [comment]
How to make this kernels？

**Comment by fenglinglwb** [comment]
Please refer to Sec.2.3 of the paper.
