### ISSUE TITLE
Reception field of Lapar method

### ISSUE THREAD

**Issue by LitleCarl** [dvlab-research/Simple-SR#8]
If I understand well, the convolution part which predicts filter coefficients could be as heavy/deep as possible.
Since the final computed filters are applied on the bicubic input  image with size of `k*k`, the image prior/info can be utilized is constrained by `k*k` size. 

So will it be the bottleneck for this model ?

**Comment by fenglinglwb** [comment]
Thanks for your interest. In my understanding, the branch of predicting filter coefficients could be deep, which is designed to extract image prior/info. As you said, we found that increasing the kernel size k*k could lead to more improvement when the upsampling scale is large,  e.g., x4 scale.

**Comment by LitleCarl** [comment]
> increasing

Thank you for quick response. BTW, have you tried predicting the filters parameter directly instead of coefficients? 
If yes, how does it compare to the method in your paper?

**Comment by fenglinglwb** [comment]
We have not tried the direct prediction of filters, but we tried to predict coefficients of learned filters. If you want to have a try, just modify the branch of predicting coefficients to predicting filters, and then apply them to the bicubic upsampled images.
